// frontend/employee-management-frontend/src/components/Contracts/ContractDetail.tsx
import { useParams, useNavigate } from "react-router-dom";
import { useState, useEffect } from "react";
import { contractService } from "../../services/contractService";
import { employeeService } from "../../services/employeeService";
import { Layout } from "../Layout/Layout";
import type { Contract } from "../../types/contract";
import type { Employee } from "../../types/employee";

export const ContractDetail = () => {
    const { id } = useParams<{ id: string }>();
    const navigate = useNavigate();
    const [contract, setContract] = useState<Contract | null>(null);
    const [employee, setEmployee] = useState<Employee | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        const fetchData = async () => {
            try {
                if (id) {
                    const contractData = await contractService.getById(id);
                    setContract(contractData);

                    const rawEmployeeId = (contractData as any).employeeId;
                    const employeeId =
                        rawEmployeeId && typeof rawEmployeeId === "object"
                            ? rawEmployeeId.id ?? rawEmployeeId._id
                            : rawEmployeeId;

                    const employeeData = await employeeService.getById(employeeId);
                    setEmployee(employeeData);
                }
            } catch (err: any) {
                console.error("Error:", err);
                setError(err.response?.data?.message || "Error al cargar contrato");
            } finally {
                setLoading(false);
            }
        };

        fetchData();
    }, [id]);

    const handleDelete = async () => {
        if (window.confirm("¿Estás seguro de que deseas eliminar este contrato?")) {
            try {
                await contractService.delete(id!);
                navigate("/contracts");
            } catch (err: any) {
                setError(err.response?.data?.message || "Error al eliminar contrato");
            }
        }
    };

    const getStatusColor = (status: string) => {
        switch (status) {
            case "APROBADO":
                return "success";
            case "ACTIVO":
                return "info";
            case "PENDIENTE":
                return "warning";
            case "RECHAZADO":
                return "danger";
            case "FINALIZADO":
                return "secondary";
            default:
                return "secondary";
        }
    };

    const getStatusText = (status: string) => {
        switch (status) {
            case "APROBADO":
                return "Aprobado";
            case "ACTIVO":
                return "Activo";
            case "PENDIENTE":
                return "Pendiente";
            case "RECHAZADO":
                return "Rechazado";
            case "FINALIZADO":
                return "Finalizado";
            default:
                return status;
        }
    };

    if (loading) {
        return (
            <Layout>
                <div className="text-center py-5">
                    <div className="spinner-border text-primary" role="status">
                        <span className="visually-hidden">Cargando...</span>
                    </div>
                    <p className="text-muted mt-3">Cargando contrato...</p>
                </div>
            </Layout>
        );
    }

    if (error || !contract || !employee) {
        return (
            <Layout>
                <div className="alert alert-danger mb-3">
                    {error || "Contrato no encontrado"}
                </div>
                <button
                    onClick={() => navigate("/contracts")}
                    className="btn btn-secondary"
                >
                    ← Volver
                </button>
            </Layout>
        );
    }

    return (
        <Layout>
            <div className="container-fluid">
                <button
                    onClick={() => navigate("/contracts")}
                    className="btn btn-outline-secondary btn-sm mb-3"
                >
                    ← Volver
                </button>

                <div className="d-flex justify-content-center">
                    <div style={{ width: "100%", maxWidth: "700px" }}>
                        <div className="card border-0 shadow-sm">
                            <div className="card-body p-5">
                                <h2 className="fw-bold mb-4">
                                    {employee.name} {employee.surname}
                                </h2>

                                <div className="row g-3 mb-4">
                                    <div className="col-md-6">
                                        <p className="text-muted small mb-1">Puesto</p>
                                        <p className="fw-semibold">{contract.position}</p>
                                    </div>
                                    <div className="col-md-6">
                                        <p className="text-muted small mb-1">Departamento</p>
                                        <p className="fw-semibold">{contract.department}</p>
                                    </div>
                                </div>

                                <div className="row g-3 mb-4">
                                    <div className="col-md-6">
                                        <p className="text-muted small mb-1">Categoría</p>
                                        <p className="fw-semibold">{contract.category}</p>
                                    </div>
                                    <div className="col-md-6">
                                        <p className="text-muted small mb-1">Tipo de Contrato</p>
                                        <p>
                                            <span className="badge bg-light text-dark">
                                                {contract.contractType}
                                            </span>
                                        </p>
                                    </div>
                                </div>

                                <div className="row g-3 mb-4">
                                    <div className="col-md-6">
                                        <p className="text-muted small mb-1">Jornada</p>
                                        <p className="fw-semibold">{contract.workdayType}</p>
                                    </div>
                                    <div className="col-md-6">
                                        <p className="text-muted small mb-1">Estado</p>
                                        <p>
                                            <span className={`badge bg-${getStatusColor(contract.status)}`}>
                                                {getStatusText(contract.status)}
                                            </span>
                                        </p>
                                    </div>
                                </div>

                                <div className="row g-3 mb-4">
                                    <div className="col-md-6">
                                        <p className="text-muted small mb-1">Salario ({contract.salaryType})</p>
                                        <p className="fw-semibold">{contract.salaryAmount.toFixed(2)} €</p>
                                    </div>
                                    <div className="col-md-6">
                                        <p className="text-muted small mb-1">Inicio del Contrato</p>
                                        <p className="fw-semibold">
                                            {new Date(contract.startDate).toLocaleDateString("es-ES")}
                                        </p>
                                    </div>
                                </div>

                                <div className="row g-3 mb-4">
                                    <div className="col-12">
                                        <p className="text-muted small mb-1">Fin del Contrato</p>
                                        <p className="fw-semibold">
                                            {contract.endDate
                                                ? new Date(contract.endDate).toLocaleDateString("es-ES")
                                                : "Sin fecha de fin"}
                                        </p>
                                    </div>
                                </div>

                                <hr />

                                <div className="d-flex gap-2 flex-wrap">
                                    <button
                                        onClick={() => navigate(`/contracts/${(contract as any).id}/edit`)}
                                        className="btn btn-warning flex-grow-1"
                                    >
                                        Editar
                                    </button>
                                    <button
                                        onClick={handleDelete}
                                        className="btn btn-danger flex-grow-1"
                                    >
                                        Eliminar
                                    </button>
                                    <button
                                        onClick={() => navigate("/contracts")}
                                        className="btn btn-secondary flex-grow-1"
                                    >
                                        Cerrar
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </Layout>
    );
};

// frontend-angular/src/app/features/contracts/detail/contract-detail.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, ActivatedRoute, Router } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { ContractService } from '../../../core/services/contract.service';
import { NotificationService } from '../../../core/services/notification.service';
import { AuthService } from '../../../core/services/auth.service';
import { Contract, ContractStatus } from '../../../core/models/contract.model';

@Component({
  selector: 'app-contract-detail',
  standalone: true,
  imports: [CommonModule, RouterLink, MatIconModule, MatProgressSpinnerModule],
  templateUrl: './contract-detail.component.html',
  styleUrl: './contract-detail.component.scss'
})
export class ContractDetailComponent implements OnInit {
  loading = signal(true);
  contract = signal<Contract | null>(null);
  updatingStatus = signal(false);

  readonly statuses: ContractStatus[] = ['PENDIENTE', 'APROBADO', 'ACTIVO', 'RECHAZADO', 'FINALIZADO'];

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private contractService: ContractService,
    private notify: NotificationService,
    public auth: AuthService
  ) {}

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id')!;
    this.contractService.getById(id).subscribe({
      next: (c) => { this.contract.set(c); this.loading.set(false); },
      error: () => { this.notify.error('Contrato no encontrado'); this.router.navigate(['/contracts']); }
    });
  }

  changeStatus(status: ContractStatus): void {
    const c = this.contract();
    if (!c) return;
    this.updatingStatus.set(true);
    this.contractService.updateStatus(c._id ?? c.id!, status).subscribe({
      next: (updated) => {
        this.contract.set(updated);
        this.notify.success(`Estado cambiado a ${status}`);
        this.updatingStatus.set(false);
      },
      error: (err) => {
        this.notify.error(err?.error?.message || 'Error al cambiar estado');
        this.updatingStatus.set(false);
      }
    });
  }

  confirmDelete(): void {
    if (!confirm('¿Eliminar este contrato?')) return;
    const c = this.contract()!;
    this.contractService.delete(c._id ?? c.id!).subscribe({
      next: () => { this.notify.success('Contrato eliminado'); this.router.navigate(['/contracts']); },
      error: (err) => this.notify.error(err?.error?.message || 'Error al eliminar')
    });
  }

  getStatusClass(s: string): string {
    const m: Record<string, string> = {
      ACTIVO: 'badge-success', PENDIENTE: 'badge-warning',
      APROBADO: 'badge-info', RECHAZADO: 'badge-danger', FINALIZADO: 'badge-secondary'
    };
    return m[s] ?? 'badge-secondary';
  }

  getId(c: Contract): string { return c._id ?? c.id ?? ''; }
}

@if (loading()) {
  <div class="loading-overlay"><mat-spinner diameter="40"></mat-spinner></div>
} @else if (contract(); as c) {
  <div class="detail-page">
    <div class="detail-header">
      <a routerLink="/contracts" class="back-link">
        <mat-icon>arrow_back</mat-icon> Contratos
      </a>
      @if (auth.isHrManager()) {
        <div class="header-actions">
          <a [routerLink]="['/contracts', getId(c), 'edit']" class="btn btn-secondary">
            <mat-icon>edit</mat-icon> Editar
          </a>
          @if (auth.isAdmin()) {
            <button class="btn btn-danger" (click)="confirmDelete()">
              <mat-icon>delete</mat-icon> Eliminar
            </button>
          }
        </div>
      }
    </div>

    <div class="card contract-header-card">
      <div class="contract-hero">
        <div class="contract-icon">
          <mat-icon>description</mat-icon>
        </div>
        <div>
          <h1>{{ c.contractType }} — {{ c.position }}</h1>
          <p>{{ c.department }}</p>
        </div>
        <div class="contract-status-area">
          <span [class]="'badge badge-lg ' + getStatusClass(c.status)">{{ c.status }}</span>
        </div>
      </div>

      @if (auth.isHrManager()) {
        <div class="status-actions">
          <span class="status-label">Cambiar estado:</span>
          @for (s of statuses; track s) {
            <button
              class="status-btn"
              [class.active]="c.status === s"
              [class]="'status-btn status-' + s.toLowerCase()"
              (click)="changeStatus(s)"
              [disabled]="c.status === s || updatingStatus()"
            >{{ s }}</button>
          }
        </div>
      }
    </div>

    <div class="info-grid">
      <div class="card info-card">
        <h3>Empleado</h3>
        @if (c.employee) {
          <div class="info-row">
            <mat-icon>person</mat-icon>
            <div>
              <span class="info-label">Nombre</span>
              <span class="info-value">{{ c.employee.name }} {{ c.employee.surname }}</span>
            </div>
          </div>
          <div class="info-row">
            <mat-icon>badge</mat-icon>
            <div>
              <span class="info-label">NIF</span>
              <span class="info-value mono">{{ c.employee.nif }}</span>
            </div>
          </div>
        } @else {
          <p class="text-muted">Sin datos del empleado</p>
        }
      </div>

      <div class="card info-card">
        <h3>Condiciones laborales</h3>
        <div class="info-row">
          <mat-icon>work</mat-icon>
          <div>
            <span class="info-label">Jornada</span>
            <span class="info-value">{{ c.workdayType }}</span>
          </div>
        </div>
        <div class="info-row">
          <mat-icon>payments</mat-icon>
          <div>
            <span class="info-label">Salario {{ c.salaryType }}</span>
            <span class="info-value salary">{{ c.salaryAmount | currency:'EUR':'symbol':'1.0-0' }}</span>
          </div>
        </div>
      </div>

      <div class="card info-card">
        <h3>Fechas</h3>
        <div class="info-row">
          <mat-icon>event</mat-icon>
          <div>
            <span class="info-label">Fecha inicio</span>
            <span class="info-value">{{ c.startDate | date:'dd/MM/yyyy' }}</span>
          </div>
        </div>
        @if (c.endDate) {
          <div class="info-row">
            <mat-icon>event_busy</mat-icon>
            <div>
              <span class="info-label">Fecha fin</span>
              <span class="info-value">{{ c.endDate | date:'dd/MM/yyyy' }}</span>
            </div>
          </div>
        }
      </div>

      <div class="card info-card">
        <h3>Clasificación</h3>
        <div class="info-row">
          <mat-icon>category</mat-icon>
          <div>
            <span class="info-label">Categoría</span>
            <span class="info-value">{{ c.category }}</span>
          </div>
        </div>
        @if (c.temporaryType) {
          <div class="info-row">
            <mat-icon>schedule</mat-icon>
            <div>
              <span class="info-label">Tipo temporal</span>
              <span class="info-value">{{ c.temporaryType }}</span>
            </div>
          </div>
        }
      </div>
    </div>
  </div>
}
